name: Monthly Review Pipeline

on:
  schedule:
    - cron: '0 2 1 * *'    # run at 02:00 UTC on day-1 of every month
  workflow_dispatch:      # also allow manual triggers

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run data cleaning
      run: python scripts/clean_data.py

    - name: Run sentiment analysis
      run: python scripts/sentiment_analysis.py

    - name: Run forecasting
      run: python scripts/forecast.py

    - name: Commit and push processed data
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add data/cleaned_reviews.xlsx data/review_sentiment_data.xlsx data/forecast_next6.xlsx
        git commit -m "Monthly update: cleaned, sentiment, forecast"
        git push
      env:
        # if your repo is private, set a PAT with write access in GitHub Secrets
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
